tap "getsentry/xcodebuildmcp"

brew "neovim"
brew "gh"
brew "xcp"
brew "xcode-build-server"
brew "xcbeautify"
brew "swiftformat"
brew "swiftlint"
brew "lazygit"
brew "git-delta"
brew "tuicr"
brew "herdr"
brew "ripgrep"
brew "fd"
brew "jq"
brew "coreutils"
brew "xcodebuildmcp"
